export const SEARCH_COMPANY_SUCCESS = "SEARCH_COMPANY_SUCCESS";
export const SEARCH_COMPANY_ERROR = "SEARCH_COMPANY_ERROR";

export const SEARCH_TABLE_SUCCESS = "SEARCH_CHART_SUCCESS";
export const SEARCH_TABLE_ERROR = "SEARCH_CHART_ERROR";

export const SEARCH_INTRADAY_SUCCESS = "SEARCH_INTRADAY_SUCCESS";
export const SEARCH_INTRADAY_ERROR = "SEARCH_INTRADAY_ERROR";